### PR TITLE
Results of the meeting with lorenzo, michael & michael

### PR DESCRIPTION
**Pull request by linaGirl**
@fxstr notable changes:
- Classes are always PascalCase (imports, exports, names, filenames)
- 17.1 is controversial. What's your stance on it?
- no leading commas

### CODE REVIEW

**Review by lkappeler — APPROVED** [review]
looks ok to me

**Comment by fxstr** [comment]
@eventEmitter It's basically fine for me. 
- 17.1: If we tend to limit a line's length, we won't get around this rule. It's consistent to have it.
- `//TODO`: Nice compromise, works for me. 

Core question: When and to what do we apply those rules? I suggest: To all new entities in current projects, as long as they are not almost completed (like e.g. Winconcept). We should not spend too much time (and therefore budget) on refactorings. 

And: It's very crucial to me that we stick to these rules for a **long** time (5+ years). I remember switching from `if(a === b)` to `if ( a === b )` back to `if (a === b)` (and now we add some new rules).  That does not make a lot of sense to me as getting used to a new standard takes time, refactorings and therefore costs.

**Comment by linaGirl** [comment]
Thanks @fxstr . I think we should apply the rules to new code or code we are refactoring, not to any old projects or modules. 

***17.1***: the discussion is not about if the statements can be split on to several lines but on how to do that.

variant a:
```
if ((foo === 123 || bar === "abc") &&
    doesItLookGoodWhenItBecomesThatLong() &&
    isThisReallyHappening()
) {
```

variant b:
```
if (
    (foo === 123 || bar === "abc") &&
    doesItLookGoodWhenItBecomesThatLong() &&
    isThisReallyHappening()
) {
```
 

And: I agree that we should stick to the rules as they are defined now. If there are going to be changes, we will have to discuss them together and apply them to ***new*** code only. In the past, I personally never had to refactor code in a relevant quantity because of rule changes. We should be enough flexible to change the rules when we learn new things or when things are changing. But yes, let's try to change as little as possible.

**Comment by fxstr** [comment]
@eventEmitter Thank you very much, I'm with you on all comments. 

I'd personally stick with Airbnb's 17.1.

**Comment by lkappeler** [comment]
About the refactoring, I think the IDEs are able to auto format the code by defined coding guidelines. Atom for example has an option to fix eslint errors on save. This would actually "refactor" the code on the fly for each file you are going to touch.

**Comment by rcky** [comment]
Yeah, IDEs support that, but be aware that the legacy codebases might be big. So the guidelines might only apply for the new projects e.g. the Lizenzmanager. Aside from that, there are mechanics to ignore certain parts of the codebase (ie. eslintignore).

P.S: I absolutely hate the linebreak in the first line of the if condition!

**Pull request merged**
